import { z } from "zod";

// -- Enums --------------------------------------------------------------------

// Keep this list in sync with WORKER_JOB_ROLES in
// packages/config/src/constants.ts. The values are stored as TEXT in
// worker_job_roles.role, so adding new entries is non-breaking — but removing
// an existing value would orphan profiles, so only ADD.
export const workerJobRoleSchema = z.enum([
  "animator",
  "fb_manager",
  "bell_boy",
  "guest_relations",
  "concierge",
  "host",
  "maitre",
  "sommelier",
  "reservations_agent",
  "maid",
  "tourism_other",
  "chef",
  "pastry_chef",
  "bartender",
  "barista",
  "lifeguard",
  "water_sports_instructor",
  "tour_guide",
  "housekeeping_supervisor",
  "airport_staff",
  "flight_attendant",
  "kitchen_assistant",
  "tourism_shop_seller",
  "receptionist",
  "waiter",
  "hotel_executive",
  "hotel_technician",
  "spa_staff",
  "tourism_employee",
  "skipper",
  "delivery_man",
  "baker",
  "butcher",
  "dishwasher",
  "buffet_staff",
  "restaurant_seller",
  "waiter_assistant",
  "restaurant_host",
  "restaurant_manager",
  "grill_cook",
  "logistics_specialist",
  "warehouse_worker",
  "driver",
  "truck_driver",
  "courier",
  "delivery_driver",
  "bus_driver",
  "taxi_driver",
  "packer",
  "dispatcher",
  "forklift_operator",
  "crane_operator",
  "merchandiser",
  "retail_director",
  "external_retail_sales",
  "sales_assistant",
  "mobile_energy_seller",
  "gas_station_seller",
  "supermarket_employee",
  "opap_employee",
  "cashier",
  "store_manager",
  "factory_worker",
  "skilled_worker",
  "iron_worker",
  "welder",
  "carpenter",
  "furniture_maker",
  "production_supervisor",
  "garment_worker",
  "machine_maintenance",
  "lathe_operator",
  "heavy_machinery_operator",
  "cnc_operator",
  "production_worker",
  "machine_operator",
  "quality_inspector",
  "project_engineer",
  "architect",
  "industrial_designer",
  "electrical_engineer",
  "science_researcher",
  "engineers_other",
  "automation_engineer",
  "electronic_engineer",
  "site_engineer",
  "production_engineer",
  "environmental_engineer",
  "mechanical_engineer",
  "civil_engineer",
  "sales_engineer",
  "food_technologist",
  "surveyor",
  "chemist",
  "chemical_engineer",
  "back_office_clerk",
  "data_entry",
  "secretary",
  "exec_secretary",
  "medical_secretary",
  "sales_secretary",
  "customer_service",
  "order_processing",
  "office_employee",
  "admin_assistant",
  "office_manager",
  "hr_assistant",
  "electrician",
  "electronics_technician",
  "technical_other",
  "mechanic",
  "boat_mechanic",
  "technical_salesperson",
  "medical_equipment_tech",
  "fiber_optics_tech",
  "security_systems_tech",
  "construction_worker",
  "plumber",
  "hvac_technician",
  "painter",
  "mason",
  "handyman",
  "technician",
  "bookkeeper",
  "internal_auditor",
  "accountant",
  "financial_analyst",
  "finance_director",
  "accounting_supervisor",
  "procurement",
  "banking",
  "public_tender_clerk",
  "accounting_clerk",
  "it_finance_admin",
  "billing_clerk",
  "payroll_specialist",
  "area_manager",
  "sales_director",
  "sales_b2b",
  "b2b_international_sales",
  "key_account_manager",
  "sales_partner",
  "purchasing_manager",
  "paramedic",
  "medical_rep",
  "doctor",
  "veterinarian",
  "midwife",
  "microbiologist",
  "nurse",
  "dentist",
  "dental_technician",
  "dental_assistant",
  "optician",
  "medical_lab_technologist",
  "pharmacy_assistant",
  "pharmacist",
  "caregiver",
  "elder_caregiver",
  "physiotherapist",
  "occupational_therapist",
  "medical_machinery_operator",
  "psychologist",
  "security_guard",
  "doorman",
  "disinfector",
  "cleaner",
  "housekeeper",
  "multilingual_call_center",
  "call_center_supervisor",
  "call_center_agent",
  "telephonist",
  "collections_agent",
  "event_planner",
  "social_media_manager",
  "social_internet_marketing",
  "journalist",
  "product_promoter",
  "marketing_specialist",
  "marketing_executive",
  "beautician",
  "gym_trainer",
  "personal_trainer",
  "nutritionist",
  "hairdresser",
  "barber",
  "massage_therapist",
  "nail_technician",
  "makeup_artist",
  "cyber_security_specialist",
  "data_scientist",
  "database_admin",
  "devops_engineer",
  "erp_crm_specialist",
  "it_support",
  "it_administrator",
  "network_admin",
  "qa_tester",
  "software_developer",
  "systems_engineer",
  "tech_support_sales",
  "web_developer",
  "web_designer",
  "data_analyst",
  "elementary_teacher",
  "special_education",
  "seminar_instructor",
  "secondary_teacher",
  "language_teacher",
  "university_professor",
  "translator",
  "kindergarten_assistant",
  "tutor",
  "teacher",
  "babysitter",
  "insurance_agent",
  "real_estate_agent",
  "account_manager",
  "project_manager",
  "executive_director",
  "business_manager",
  "hr_executive",
  "iso_consultant",
  "business_consultant",
  "espa_consultant",
  "cad_3d_designer",
  "video_editor",
  "videographer",
  "graphic_designer",
  "interior_designer",
  "actor",
  "audiovisual_music",
  "fashion_designer",
  "typographer",
  "photographer",
  "content_creator",
  "copywriter",
  "digital_marketing_specialist",
  "ecommerce_specialist",
  "ecommerce_manager",
  "seo_specialist",
  "performance_marketer",
  "eshop_admin",
  "agronomist",
  "forester",
  "gardener",
  "farm_worker",
  "lawyer",
  "paralegal",
  "legal_office_clerk",
  "shipping_executive",
  "sailor",
  "ship_engineer",
  "dj",
  "telesales",
  "other",
]);

export type WorkerJobRole = z.infer<typeof workerJobRoleSchema>;

export const availabilitySchema = z.enum([
  "immediate",
  "within_7_days",
  "seasonal",
  "part_time",
  "full_time",
]);

export const employmentTypeSchema = z.enum([
  "seasonal",
  "full_time",
  "part_time",
  "freelancer",
]);

export type Availability = z.infer<typeof availabilitySchema>;

// -- Create Worker Profile ----------------------------------------------------

export const createWorkerProfileSchema = z.object({
  fullName: z
    .string()
    .min(2, "Full name must be at least 2 characters")
    .max(100, "Full name must be at most 100 characters"),
  city: z
    .string()
    .min(2, "City must be at least 2 characters")
    .max(100, "City must be at most 100 characters"),
  region: z
    .string()
    .min(2, "Region must be at least 2 characters")
    .max(100, "Region must be at most 100 characters"),
  willingToRelocate: z.boolean(),
  jobRoles: z
    .array(workerJobRoleSchema)
    .min(1, "At least one job role is required")
    .max(5, "At most 5 job roles allowed"),
  yearsOfExperience: z
    .number()
    .min(0, "Years of experience cannot be negative")
    .max(50, "Years of experience must be at most 50"),
  languages: z.array(z.string()).min(1, "At least one language is required"),
  expectedHourlyRate: z
    .number()
    .positive("Hourly rate must be a positive number")
    .optional(),
  expectedMonthlySalary: z
    .number()
    .positive("Monthly salary must be a positive number")
    .optional(),
  availability: availabilitySchema,
  bio: z.string().max(1000, "Bio must be at most 1000 characters").optional(),
});

export type CreateWorkerProfileInput = z.infer<typeof createWorkerProfileSchema>;

// -- Update Worker Profile ----------------------------------------------------

export const updateWorkerProfileSchema = createWorkerProfileSchema.partial().extend({
  roles: z.array(workerJobRoleSchema).max(5).optional(),
  languages: z.array(z.string()).optional(),
  employmentType: employmentTypeSchema.optional(),
  isVisible: z.boolean().optional(),
  compensationType: z.enum(['hourly', 'monthly']).optional(),
  photoUrl: z.string().optional(),
  cvUrl: z.string().optional(),
  skills: z.string().optional(),
});

export type UpdateWorkerProfileInput = z.infer<typeof updateWorkerProfileSchema>;

// -- Worker Filters -----------------------------------------------------------

export const workerFilterSchema = z.object({
  roles: z.array(workerJobRoleSchema).optional(),
  region: z.string().optional(),
  language: z.string().optional(),
  availability: availabilitySchema.optional(),
  minSalary: z.number().positive().optional(),
  maxSalary: z.number().positive().optional(),
  willingToRelocate: z.boolean().optional(),
  verifiedOnly: z.boolean().optional(),
});

export type WorkerFilter = z.infer<typeof workerFilterSchema>;
