export const APP_NAME = 'StaffNow';
export const DOMAIN = 'staffnow.gr';
export const API_DOMAIN = 'api.staffnow.gr';

export const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
export const ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp'];
export const ALLOWED_DOC_TYPES = ['application/pdf', 'image/jpeg', 'image/png'];
export const MAX_BIO_LENGTH = 1000;
export const MAX_JOB_DESCRIPTION_LENGTH = 5000;

export const REGIONS_GREECE = [
  'Αττική',
  'Θεσσαλονίκη',
  'Κρήτη',
  'Δωδεκάνησα',
  'Κυκλάδες',
  'Κέρκυρα',
  'Ζάκυνθος',
  'Χαλκιδική',
  'Πελοπόννησος',
  'Ιόνια Νησιά',
  'Βόρειο Αιγαίο',
  'Νότιο Αιγαίο',
  'Ήπειρος',
  'Θεσσαλία',
  'Στερεά Ελλάδα',
  'Δυτική Ελλάδα',
  'Δυτική Μακεδονία',
  'Ανατολική Μακεδονία και Θράκη',
] as const;

/**
 * Common countries for job listings & worker preferences.
 * `code` = ISO 3166-1 alpha-2 (used as DB value & for flag emoji).
 * `flag` = Unicode regional indicator emoji (computed at usage time, but kept here for fallback).
 * Greece is the default — listed first.
 */
export const COUNTRIES_COMMON = [
  { code: 'GR', label: 'Ελλάδα', flag: '🇬🇷' },
  { code: 'CY', label: 'Κύπρος', flag: '🇨🇾' },
  { code: 'DE', label: 'Γερμανία', flag: '🇩🇪' },
  { code: 'UK', label: 'Ηνωμένο Βασίλειο', flag: '🇬🇧' },
  { code: 'NL', label: 'Ολλανδία', flag: '🇳🇱' },
  { code: 'BE', label: 'Βέλγιο', flag: '🇧🇪' },
  { code: 'FR', label: 'Γαλλία', flag: '🇫🇷' },
  { code: 'IT', label: 'Ιταλία', flag: '🇮🇹' },
  { code: 'ES', label: 'Ισπανία', flag: '🇪🇸' },
  { code: 'PT', label: 'Πορτογαλία', flag: '🇵🇹' },
  { code: 'AT', label: 'Αυστρία', flag: '🇦🇹' },
  { code: 'CH', label: 'Ελβετία', flag: '🇨🇭' },
  { code: 'SE', label: 'Σουηδία', flag: '🇸🇪' },
  { code: 'NO', label: 'Νορβηγία', flag: '🇳🇴' },
  { code: 'FI', label: 'Φινλανδία', flag: '🇫🇮' },
  { code: 'DK', label: 'Δανία', flag: '🇩🇰' },
  { code: 'IE', label: 'Ιρλανδία', flag: '🇮🇪' },
  { code: 'PL', label: 'Πολωνία', flag: '🇵🇱' },
  { code: 'CZ', label: 'Τσεχία', flag: '🇨🇿' },
  { code: 'MT', label: 'Μάλτα', flag: '🇲🇹' },
  { code: 'LU', label: 'Λουξεμβούργο', flag: '🇱🇺' },
  { code: 'AE', label: 'ΗΑΕ (Ντουμπάι)', flag: '🇦🇪' },
  { code: 'US', label: 'ΗΠΑ', flag: '🇺🇸' },
  { code: 'CA', label: 'Καναδάς', flag: '🇨🇦' },
  { code: 'AU', label: 'Αυστραλία', flag: '🇦🇺' },
  { code: 'OTHER', label: 'Άλλη χώρα', flag: '🌍' },
] as const;

export const COUNTRIES_BY_CODE: Record<string, { label: string; flag: string }> = Object.fromEntries(
  COUNTRIES_COMMON.map((c) => [c.code, { label: c.label, flag: c.flag }]),
);

export const LANGUAGES_COMMON = [
  'Ελληνικά',
  'English',
  'Deutsch',
  'Français',
  'Italiano',
  'Español',
  'Русский',
  'العربية',
  '中文',
  'Shqip',
  'Български',
  'Română',
] as const;

// ============================================================================
// WORKER_JOB_ROLES
// Plain string IDs (snake_case). Categorisation matches JobFind.gr's 24
// professional categories so workers/employers find familiar specialties.
// IMPORTANT: keep this list in sync with `workerJobRoleSchema` in
// packages/validation/src/worker.ts — the API rejects unknown values.
// Adding entries is non-breaking. Removing/renaming an existing ID would
// orphan existing profile/job records, so only ADD.
// ============================================================================
export const WORKER_JOB_ROLES = [
  // -- Τουρισμός - Ξενοδοχεία
  'animator',
  'fb_manager',
  'bell_boy',
  'guest_relations',
  'concierge',
  'host',
  'maitre',
  'sommelier',
  'reservations_agent',
  'maid',
  'tourism_other',
  'chef',
  'pastry_chef',
  'bartender',
  'barista',
  'lifeguard',
  'water_sports_instructor',
  'tour_guide',
  'housekeeping_supervisor',
  'airport_staff',
  'flight_attendant',
  'kitchen_assistant',
  'tourism_shop_seller',
  'receptionist',
  'waiter',
  'hotel_executive',
  'hotel_technician',
  'spa_staff',
  'tourism_employee',
  'skipper',
  // -- Εστίαση
  'delivery_man',
  'baker',
  'butcher',
  'dishwasher',
  'buffet_staff',
  'restaurant_seller',
  'waiter_assistant',
  'restaurant_host',
  'restaurant_manager',
  'grill_cook',
  // -- Logistics - Αποθήκη - Μεταφορές
  'logistics_specialist',
  'warehouse_worker',
  'driver',
  'truck_driver',
  'courier',
  'delivery_driver',
  'bus_driver',
  'taxi_driver',
  'packer',
  'dispatcher',
  'forklift_operator',
  'crane_operator',
  // -- Πωλήσεις Λιανικής - Merchandising
  'merchandiser',
  'retail_director',
  'external_retail_sales',
  'sales_assistant',
  'mobile_energy_seller',
  'gas_station_seller',
  'supermarket_employee',
  'opap_employee',
  'cashier',
  'store_manager',
  // -- Παραγωγή - Εργάτες - Τεχνίτες
  'factory_worker',
  'skilled_worker',
  'iron_worker',
  'welder',
  'carpenter',
  'furniture_maker',
  'production_supervisor',
  'garment_worker',
  'machine_maintenance',
  'lathe_operator',
  'heavy_machinery_operator',
  'cnc_operator',
  'production_worker',
  'machine_operator',
  'quality_inspector',
  // -- Μηχανικοί ΑΕΙ / ΤΕΙ - Επιστήμες
  'project_engineer',
  'architect',
  'industrial_designer',
  'electrical_engineer',
  'science_researcher',
  'engineers_other',
  'automation_engineer',
  'electronic_engineer',
  'site_engineer',
  'production_engineer',
  'environmental_engineer',
  'mechanical_engineer',
  'civil_engineer',
  'sales_engineer',
  'food_technologist',
  'surveyor',
  'chemist',
  'chemical_engineer',
  // -- Γραμματειακή Υποστήριξη - Υπάλληλοι Γραφείου
  'back_office_clerk',
  'data_entry',
  'secretary',
  'exec_secretary',
  'medical_secretary',
  'sales_secretary',
  'customer_service',
  'order_processing',
  'office_employee',
  'admin_assistant',
  'office_manager',
  'hr_assistant',
  // -- Τεχνικοί ΕΠΑΛ / ΙΕΚ - Βοηθοί
  'electrician',
  'electronics_technician',
  'technical_other',
  'mechanic',
  'boat_mechanic',
  'technical_salesperson',
  'medical_equipment_tech',
  'fiber_optics_tech',
  'security_systems_tech',
  'construction_worker',
  'plumber',
  'hvac_technician',
  'painter',
  'mason',
  'handyman',
  'technician',
  // -- Λογιστήριο - Οικονομική Διεύθυνση
  'bookkeeper',
  'internal_auditor',
  'accountant',
  'financial_analyst',
  'finance_director',
  'accounting_supervisor',
  'procurement',
  'banking',
  'public_tender_clerk',
  'accounting_clerk',
  'it_finance_admin',
  'billing_clerk',
  'payroll_specialist',
  // -- Πωλήσεις Χονδρικής (B2B)
  'area_manager',
  'sales_director',
  'sales_b2b',
  'b2b_international_sales',
  'key_account_manager',
  'sales_partner',
  'purchasing_manager',
  // -- Υγεία
  'paramedic',
  'medical_rep',
  'doctor',
  'veterinarian',
  'midwife',
  'microbiologist',
  'nurse',
  'dentist',
  'dental_technician',
  'dental_assistant',
  'optician',
  'medical_lab_technologist',
  'pharmacy_assistant',
  'pharmacist',
  'caregiver',
  'elder_caregiver',
  'physiotherapist',
  'occupational_therapist',
  'medical_machinery_operator',
  'psychologist',
  // -- Προσωπικό Ασφαλείας - Υπηρεσίες Καθαριότητας
  'security_guard',
  'doorman',
  'disinfector',
  'cleaner',
  'housekeeper',
  // -- Τηλεφωνικές Υπηρεσίες
  'multilingual_call_center',
  'call_center_supervisor',
  'call_center_agent',
  'telephonist',
  'collections_agent',
  // -- Marketing - Διαφήμιση - Επικοινωνία
  'event_planner',
  'social_media_manager',
  'social_internet_marketing',
  'journalist',
  'product_promoter',
  'marketing_specialist',
  'marketing_executive',
  // -- Ομορφιά, Περιποίηση - Fitness
  'beautician',
  'gym_trainer',
  'personal_trainer',
  'nutritionist',
  'hairdresser',
  'barber',
  'massage_therapist',
  'nail_technician',
  'makeup_artist',
  // -- Πληροφορική - Προγραμματιστές
  'cyber_security_specialist',
  'data_scientist',
  'database_admin',
  'devops_engineer',
  'erp_crm_specialist',
  'it_support',
  'it_administrator',
  'network_admin',
  'qa_tester',
  'software_developer',
  'systems_engineer',
  'tech_support_sales',
  'web_developer',
  'web_designer',
  'data_analyst',
  // -- Εκπαίδευση
  'elementary_teacher',
  'special_education',
  'seminar_instructor',
  'secondary_teacher',
  'language_teacher',
  'university_professor',
  'translator',
  'kindergarten_assistant',
  'tutor',
  'teacher',
  'babysitter',
  // -- Ασφαλιστικά - Real Estate
  'insurance_agent',
  'real_estate_agent',
  // -- Διοίκηση Επιχειρήσεων - HR - Στελέχη
  'account_manager',
  'project_manager',
  'executive_director',
  'business_manager',
  'hr_executive',
  'iso_consultant',
  'business_consultant',
  'espa_consultant',
  // -- Design - Photo - Video - Audio - Arts
  'cad_3d_designer',
  'video_editor',
  'videographer',
  'graphic_designer',
  'interior_designer',
  'actor',
  'audiovisual_music',
  'fashion_designer',
  'typographer',
  'photographer',
  // -- Digital Marketing - Ecommerce - Design
  'content_creator',
  'copywriter',
  'digital_marketing_specialist',
  'ecommerce_specialist',
  'ecommerce_manager',
  'seo_specialist',
  'performance_marketer',
  'eshop_admin',
  // -- Αγροτικά
  'agronomist',
  'forester',
  'gardener',
  'farm_worker',
  // -- Νομικά
  'lawyer',
  'paralegal',
  'legal_office_clerk',
  // -- Ναυτιλία
  'shipping_executive',
  'sailor',
  'ship_engineer',
  // -- Backwards-compat (legacy IDs kept valid in DB; not shown in groups)
  'dj',
  'telesales',
  // -- Άλλα
  'other',
] as const;

export const WORKER_JOB_ROLE_LABELS_EL: Record<string, string> = {
  // Τουρισμός - Ξενοδοχεία
  animator: 'Animator / Personal Trainer',
  fb_manager: 'F&B / Restaurant Manager / Captain',
  bell_boy: 'Groom / Bell Boy',
  guest_relations: 'Guest Relations',
  concierge: 'Concierge',
  host: 'Host',
  maitre: 'Maitre',
  sommelier: 'Sommelier',
  reservations_agent: 'Reservations Agent',
  maid: 'Καμαριέρα',
  tourism_other: 'Λοιπές Ειδικότητες Τουρισμού',
  chef: 'Μάγειρας / Chef',
  pastry_chef: 'Ζαχαροπλάστης',
  bartender: 'Bartender',
  barista: 'Μπαρίστα',
  lifeguard: 'Ναυαγοσώστης',
  water_sports_instructor: 'Θαλάσσια Σπορ',
  tour_guide: 'Ξεναγός',
  housekeeping_supervisor: 'Προϊστάμενος/η Ορόφων',
  airport_staff: 'Προσωπικό Αεροδρομίου',
  flight_attendant: 'Αεροσυνοδός',
  kitchen_assistant: 'Βοηθός Κουζίνας',
  tourism_shop_seller: 'Πωλητής Τουριστικών Καταστημάτων',
  receptionist: 'Ρεσεψιονίστ / Υπάλληλος Υποδοχής',
  waiter: 'Σερβιτόρος/α',
  hotel_executive: 'Στέλεχος Ξενοδοχειακών Μονάδων',
  hotel_technician: 'Τεχνικός Ξενοδοχείου',
  spa_staff: 'Υπάλληλος SPA',
  tourism_employee: 'Υπάλληλος Τουριστικής Επιχείρησης',
  skipper: 'Skipper / Χειριστής Σκάφους',
  // Εστίαση
  delivery_man: 'Delivery',
  baker: 'Αρτοποιός',
  butcher: 'Κρεοπώλης',
  dishwasher: 'Λαντζιέρης/α',
  buffet_staff: 'Μπουφέ',
  restaurant_seller: 'Πωλητής Καταστήματος Εστίασης',
  waiter_assistant: 'Βοηθός Σερβιτόρου',
  restaurant_host: 'Υπάλληλος Υποδοχής Εστίασης',
  restaurant_manager: 'Υπεύθυνος Καταστήματος Εστίασης',
  grill_cook: 'Ψήστης / Τυλιχτής',
  // Logistics - Αποθήκη - Μεταφορές
  logistics_specialist: 'Logistics / Προμήθειες / Εξαγωγές',
  warehouse_worker: 'Αποθηκάριος',
  driver: 'Οδηγός',
  truck_driver: 'Οδηγός Φορτηγού (Γ\'-Ε\')',
  courier: 'Courier (δικύκλου)',
  delivery_driver: 'Διανομέας',
  bus_driver: 'Οδηγός Λεωφορείου',
  taxi_driver: 'Οδηγός Ταξί',
  packer: 'Συσκευαστής',
  dispatcher: 'Dispatcher',
  forklift_operator: 'Χειριστής Κλαρκ',
  crane_operator: 'Χειριστής Ανυψωτικών',
  // Πωλήσεις Λιανικής - Merchandising
  merchandiser: 'Merchandiser',
  retail_director: 'Διευθυντής Καταστήματος',
  external_retail_sales: 'Εξωτερικός Πωλητής Λιανικής',
  sales_assistant: 'Πωλητής/τρια Καταστήματος',
  mobile_energy_seller: 'Πωλητής Κινητής/Ενέργειας',
  gas_station_seller: 'Πωλητής Πρατηρίου',
  supermarket_employee: 'Υπάλληλος Super Market',
  opap_employee: 'Υπάλληλος ΟΠΑΠ',
  cashier: 'Ταμίας',
  store_manager: 'Υπεύθυνος Καταστήματος',
  // Παραγωγή - Εργάτες - Τεχνίτες
  factory_worker: 'Εργάτης',
  skilled_worker: 'Εργατοτεχνίτης',
  iron_worker: 'Σιδεράς',
  welder: 'Ηλεκτροσυγκολλητής',
  carpenter: 'Ξυλουργός',
  furniture_maker: 'Επιπλοποιός',
  production_supervisor: 'Προϊστάμενος Παραγωγής',
  garment_worker: 'Παραγωγή Ενδυμάτων',
  machine_maintenance: 'Συντηρητής Μηχανών',
  lathe_operator: 'Τορναδόρος / Μηχανουργείο',
  heavy_machinery_operator: 'Χειριστής Μηχανήματος Έργου',
  cnc_operator: 'Χειριστής CNC',
  production_worker: 'Εργάτης Παραγωγής',
  machine_operator: 'Χειριστής Μηχανήματος',
  quality_inspector: 'Έλεγχος Ποιότητας',
  // Μηχανικοί ΑΕΙ / ΤΕΙ - Επιστήμες
  project_engineer: 'Project Engineer',
  architect: 'Αρχιτέκτονας',
  industrial_designer: 'Βιομηχανικός Σχεδιαστής',
  electrical_engineer: 'Ηλεκτρολόγος Μηχανικός',
  science_researcher: 'Θετικές Επιστήμες',
  engineers_other: 'Λοιπές Ειδικότητες Μηχανικών',
  automation_engineer: 'Μηχανικός Αυτοματισμού',
  electronic_engineer: 'Ηλεκτρονικός Μηχανικός',
  site_engineer: 'Μηχανικός Εργοταξίου',
  production_engineer: 'Μηχανικός Παραγωγής',
  environmental_engineer: 'Μηχανικός Περιβάλλοντος',
  mechanical_engineer: 'Μηχανολόγος Μηχανικός',
  civil_engineer: 'Πολιτικός Μηχανικός',
  sales_engineer: 'Πωλητής Μηχανικός',
  food_technologist: 'Τεχνολόγος Τροφίμων',
  surveyor: 'Τοπογράφος Μηχανικός',
  chemist: 'Χημικός',
  chemical_engineer: 'Χημικός Μηχανικός',
  // Γραμματειακή Υποστήριξη - Υπάλληλοι Γραφείου
  back_office_clerk: 'Back Office',
  data_entry: 'Data Entry',
  secretary: 'Γραμματέας',
  exec_secretary: 'Γραμματέας Διοίκησης',
  medical_secretary: 'Γραμματέας Ιατρείου',
  sales_secretary: 'Γραμματέας Πωλήσεων',
  customer_service: 'Εξυπηρέτηση Πελατών',
  order_processing: 'Παραγγελιοληψία',
  office_employee: 'Υπάλληλος Γραφείου',
  admin_assistant: 'Διοικητικός Υπάλληλος',
  office_manager: 'Office Manager',
  hr_assistant: 'Βοηθός HR',
  // Τεχνικοί ΕΠΑΛ / ΙΕΚ - Βοηθοί
  electrician: 'Ηλεκτρολόγος',
  electronics_technician: 'Ηλεκτρονικός',
  technical_other: 'Λοιπές Ειδικότητες Τεχνικών',
  mechanic: 'Μηχανικός Αυτοκινήτων',
  boat_mechanic: 'Μηχανικός Σκαφών',
  technical_salesperson: 'Πωλητής / Υπάλληλος Τεχνικός',
  medical_equipment_tech: 'Τεχνικός Ιατρικών Οργάνων',
  fiber_optics_tech: 'Τεχνικός Οπτικών Ινών',
  security_systems_tech: 'Τεχνικός Συστημάτων Ασφαλείας',
  construction_worker: 'Τεχνίτης Οικοδομικών Εργασιών',
  plumber: 'Υδραυλικός',
  hvac_technician: 'Ψυκτικός / HVAC',
  painter: 'Ελαιοχρωματιστής',
  mason: 'Κτίστης',
  handyman: 'Μάστορας Γενικών Καθηκόντων',
  technician: 'Τεχνικός',
  // Λογιστήριο - Οικονομική Διεύθυνση
  bookkeeper: 'Βοηθός Λογιστή',
  internal_auditor: 'Εσωτερικός Ελεγκτής / Auditor',
  accountant: 'Λογιστής',
  financial_analyst: 'Οικονομικός Αναλυτής',
  finance_director: 'Οικονομικός Διευθυντής',
  accounting_supervisor: 'Προϊστάμενος Λογιστηρίου',
  procurement: 'Προμήθειες / Εισαγωγές',
  banking: 'Τραπεζικά / Banking',
  public_tender_clerk: 'Διαγωνισμοί Δημοσίου',
  accounting_clerk: 'Υπάλληλος Λογιστηρίου',
  it_finance_admin: 'Μηχανογράφηση',
  billing_clerk: 'Τιμολόγηση',
  payroll_specialist: 'Μισθοδοσία',
  // Πωλήσεις Χονδρικής (B2B)
  area_manager: 'Area Manager',
  sales_director: 'Διευθυντής Πωλήσεων',
  sales_b2b: 'Πωλητής B2B (Ελλάδας)',
  b2b_international_sales: 'Πωλητής B2B (Εξωτερικού)',
  key_account_manager: 'Key Account Manager',
  sales_partner: 'Συνεργάτης / Αντιπρόσωπος',
  purchasing_manager: 'Υπεύθυνος Αγορών',
  // Υγεία
  paramedic: 'Διασώστης / Πλήρωμα Ασθενοφόρου',
  medical_rep: 'Ιατρικός Επισκέπτης',
  doctor: 'Ιατρός',
  veterinarian: 'Κτηνίατρος',
  midwife: 'Μαία',
  microbiologist: 'Μικροβιολόγος / Βιολόγος',
  nurse: 'Νοσηλευτής/τρια',
  dentist: 'Οδοντίατρος',
  dental_technician: 'Οδοντοτεχνίτης',
  dental_assistant: 'Βοηθός Οδοντιάτρου',
  optician: 'Οπτικός',
  medical_lab_technologist: 'Τεχνολόγος Ιατρικών Εργαστηρίων',
  pharmacy_assistant: 'Βοηθός Φαρμακείου',
  pharmacist: 'Φαρμακοποιός',
  caregiver: 'Φροντιστής/τρια',
  elder_caregiver: 'Φροντιστής Ηλικιωμένων',
  physiotherapist: 'Φυσικοθεραπευτής',
  occupational_therapist: 'Εργοθεραπευτής',
  medical_machinery_operator: 'Χειριστής Ιατρικών Μηχανημάτων',
  psychologist: 'Ψυχολόγος',
  // Προσωπικό Ασφαλείας - Υπηρεσίες Καθαριότητας
  security_guard: 'Security / Φύλακας',
  doorman: 'Πορτιέρης',
  disinfector: 'Απολυμαντής',
  cleaner: 'Καθαριστής/ια',
  housekeeper: 'Οικιακή Βοηθός',
  // Τηλεφωνικές Υπηρεσίες
  multilingual_call_center: 'Ξενόγλωσσος Σύμβουλος Call Center',
  call_center_supervisor: 'Προϊστάμενος Call Center',
  call_center_agent: 'Call Center Agent',
  telephonist: 'Τηλεφωνητής/τρια',
  collections_agent: 'Υπάλληλος Ληξιπρόθεσμων Οφειλών',
  // Marketing - Διαφήμιση - Επικοινωνία
  event_planner: 'Event Planner',
  social_media_manager: 'Social Media Manager',
  social_internet_marketing: 'Social Media & Internet Marketing',
  journalist: 'Δημοσιογράφος',
  product_promoter: 'Προώθηση Προϊόντων',
  marketing_specialist: 'Marketing Specialist',
  marketing_executive: 'Στέλεχος Marketing',
  // Ομορφιά, Περιποίηση - Fitness
  beautician: 'Αισθητικός',
  gym_trainer: 'Γυμναστής/τρια',
  personal_trainer: 'Personal Trainer',
  nutritionist: 'Διαιτολόγος',
  hairdresser: 'Κομμωτής/τρια',
  barber: 'Barber',
  massage_therapist: 'Μασέρ',
  nail_technician: 'Τεχνίτρια Νυχιών',
  makeup_artist: 'Make-up Artist',
  // Πληροφορική - Προγραμματιστές
  cyber_security_specialist: 'Cyber Security',
  data_scientist: 'Data Science & Analytics',
  database_admin: 'Database Administrator',
  devops_engineer: 'DevOps Engineer',
  erp_crm_specialist: 'ERP / CRM',
  it_support: 'IT Support',
  it_administrator: 'IT Administrator / Δίκτυα',
  network_admin: 'Network Admin',
  qa_tester: 'QA Engineer',
  software_developer: 'Software Developer',
  systems_engineer: 'Systems Engineer',
  tech_support_sales: 'Technical Support / Sales',
  web_developer: 'Web Developer',
  web_designer: 'Web Designer',
  data_analyst: 'Data Analyst',
  // Εκπαίδευση
  elementary_teacher: 'Δάσκαλος / Παιδαγωγός',
  special_education: 'Ειδική Αγωγή',
  seminar_instructor: 'Εισηγητής Σεμιναρίων',
  secondary_teacher: 'Καθηγητής Δευτεροβάθμιας',
  language_teacher: 'Καθηγητής Ξένων Γλωσσών',
  university_professor: 'Καθηγητής Τριτοβάθμιας',
  translator: 'Μεταφραστής',
  kindergarten_assistant: 'Νηπιαγωγός / Βρεφονηπιοκόμος',
  tutor: 'Δάσκαλος Ιδιαίτερων',
  teacher: 'Εκπαιδευτικός',
  babysitter: 'Babysitter',
  // Ασφαλιστικά - Real Estate
  insurance_agent: 'Ασφαλιστής / Χρηματοοικονομικός Σύμβουλος',
  real_estate_agent: 'Μεσίτης Ακινήτων',
  // Διοίκηση Επιχειρήσεων - HR - Στελέχη
  account_manager: 'Account Manager',
  project_manager: 'Project Manager',
  executive_director: 'Διευθυντής / Διοικητικό Στέλεχος',
  business_manager: 'Διευθυντής/τρια',
  hr_executive: 'Στέλεχος Ανθρώπινου Δυναμικού (HR)',
  iso_consultant: 'Σύμβουλος ISO',
  business_consultant: 'Σύμβουλος Επιχειρήσεων',
  espa_consultant: 'Σύμβουλος ΕΣΠΑ',
  // Design - Photo - Video - Audio - Arts
  cad_3d_designer: '3D / CAD Designer',
  video_editor: 'Video Editor',
  videographer: 'Videographer',
  graphic_designer: 'Γραφίστας',
  interior_designer: 'Διακοσμητής',
  actor: 'Ηθοποιός',
  audiovisual_music: 'Οπτικοακουστικά / Μουσική Τεχνολογία',
  fashion_designer: 'Σχεδιαστής Μόδας',
  typographer: 'Τυπογράφος',
  photographer: 'Φωτογράφος',
  // Digital Marketing - Ecommerce - Design
  content_creator: 'Content Creator',
  copywriter: 'Copywriter',
  digital_marketing_specialist: 'Digital Marketing',
  ecommerce_specialist: 'E-commerce Specialist',
  ecommerce_manager: 'E-commerce Manager',
  seo_specialist: 'SEO Specialist',
  performance_marketer: 'Performance Marketer',
  eshop_admin: 'Διαχειριστής E-Shop',
  // Αγροτικά
  agronomist: 'Γεωπόνος',
  forester: 'Δασολόγος',
  gardener: 'Κηπουρός',
  farm_worker: 'Αγρεργάτης',
  // Νομικά
  lawyer: 'Δικηγόρος',
  paralegal: 'Παραλεγάλιστας',
  legal_office_clerk: 'Υπάλληλος Δικηγορικού Γραφείου',
  // Ναυτιλία
  shipping_executive: 'Στέλεχος Ναυτιλιακής Επιχείρησης',
  sailor: 'Ναυτικός',
  ship_engineer: 'Μηχανικός Πλοίου',
  // Άλλα — backwards-compat (kept valid for legacy DB rows; not shown in groups)
  telesales: 'Telesales',
  dj: 'DJ',
  other: 'Άλλο',
};

/**
 * Industry groupings — mirror JobFind.gr's 24 professional categories so
 * workers/employers find familiar specialties. The picker UI iterates these.
 * Roles not present here (e.g. legacy IDs like 'telesales', 'dj') are still
 * valid in the schema but hidden from the picker.
 */
export const WORKER_JOB_ROLE_GROUPS: Array<{ id: string; label: string; roles: readonly string[] }> = [
  {
    id: 'tourism_hotels',
    label: 'Τουρισμός - Ξενοδοχεία',
    roles: [
      'animator', 'fb_manager', 'bell_boy', 'guest_relations', 'concierge', 'host',
      'maitre', 'sommelier', 'reservations_agent', 'maid', 'tourism_other',
      'chef', 'pastry_chef', 'bartender', 'barista', 'lifeguard',
      'water_sports_instructor', 'tour_guide', 'housekeeping_supervisor',
      'airport_staff', 'flight_attendant', 'kitchen_assistant', 'tourism_shop_seller',
      'receptionist', 'waiter', 'hotel_executive', 'hotel_technician', 'spa_staff',
      'tourism_employee', 'skipper',
    ],
  },
  {
    id: 'food_service',
    label: 'Εστίαση',
    roles: [
      'bartender', 'barista', 'delivery_man', 'kitchen_assistant', 'pastry_chef',
      'baker', 'butcher', 'dishwasher', 'chef', 'buffet_staff', 'restaurant_seller',
      'waiter', 'waiter_assistant', 'restaurant_host', 'restaurant_manager', 'grill_cook',
    ],
  },
  {
    id: 'logistics_transport',
    label: 'Logistics - Αποθήκη - Μεταφορές',
    roles: [
      'logistics_specialist', 'warehouse_worker', 'driver', 'truck_driver', 'courier',
      'delivery_driver', 'bus_driver', 'taxi_driver', 'packer', 'dispatcher',
      'forklift_operator', 'crane_operator',
    ],
  },
  {
    id: 'retail_sales',
    label: 'Πωλήσεις Λιανικής - Merchandising',
    roles: [
      'merchandiser', 'retail_director', 'external_retail_sales', 'sales_assistant',
      'mobile_energy_seller', 'gas_station_seller', 'supermarket_employee',
      'opap_employee', 'cashier', 'store_manager',
    ],
  },
  {
    id: 'production_workers',
    label: 'Παραγωγή - Εργάτες - Τεχνίτες',
    roles: [
      'factory_worker', 'skilled_worker', 'iron_worker', 'welder', 'carpenter',
      'furniture_maker', 'production_supervisor', 'garment_worker', 'machine_maintenance',
      'lathe_operator', 'heavy_machinery_operator', 'cnc_operator', 'production_worker',
      'machine_operator', 'quality_inspector',
    ],
  },
  {
    id: 'engineering',
    label: 'Μηχανικοί ΑΕΙ/ΤΕΙ - Επιστήμες',
    roles: [
      'project_engineer', 'architect', 'industrial_designer', 'electrical_engineer',
      'science_researcher', 'engineers_other', 'automation_engineer', 'electronic_engineer',
      'site_engineer', 'production_engineer', 'environmental_engineer',
      'mechanical_engineer', 'civil_engineer', 'sales_engineer', 'food_technologist',
      'surveyor', 'chemist', 'chemical_engineer',
    ],
  },
  {
    id: 'office_admin',
    label: 'Γραμματειακή Υποστήριξη - Γραφείο',
    roles: [
      'back_office_clerk', 'data_entry', 'secretary', 'exec_secretary',
      'medical_secretary', 'sales_secretary', 'customer_service', 'order_processing',
      'office_employee', 'admin_assistant', 'office_manager', 'hr_assistant',
    ],
  },
  {
    id: 'tech_iek',
    label: 'Τεχνικοί ΕΠΑΛ/ΙΕΚ - Βοηθοί',
    roles: [
      'electrician', 'electronics_technician', 'technical_other', 'mechanic',
      'boat_mechanic', 'technical_salesperson', 'medical_equipment_tech',
      'fiber_optics_tech', 'security_systems_tech', 'construction_worker',
      'plumber', 'hvac_technician', 'painter', 'mason', 'handyman', 'technician',
    ],
  },
  {
    id: 'finance',
    label: 'Λογιστήριο - Οικονομική Διεύθυνση',
    roles: [
      'bookkeeper', 'internal_auditor', 'accountant', 'financial_analyst',
      'finance_director', 'accounting_supervisor', 'procurement', 'banking',
      'public_tender_clerk', 'accounting_clerk', 'it_finance_admin', 'billing_clerk',
      'payroll_specialist',
    ],
  },
  {
    id: 'wholesale_b2b',
    label: 'Πωλήσεις Χονδρικής (B2B)',
    roles: [
      'area_manager', 'sales_director', 'sales_b2b', 'b2b_international_sales',
      'key_account_manager', 'sales_partner', 'purchasing_manager',
    ],
  },
  {
    id: 'health',
    label: 'Υγεία',
    roles: [
      'paramedic', 'medical_rep', 'doctor', 'veterinarian', 'midwife',
      'microbiologist', 'nurse', 'dentist', 'dental_technician', 'dental_assistant',
      'optician', 'medical_lab_technologist', 'pharmacy_assistant', 'pharmacist',
      'caregiver', 'elder_caregiver', 'physiotherapist', 'occupational_therapist',
      'medical_machinery_operator', 'psychologist',
    ],
  },
  {
    id: 'security_cleaning',
    label: 'Ασφάλεια - Καθαριότητα',
    roles: ['security_guard', 'doorman', 'disinfector', 'cleaner', 'housekeeper'],
  },
  {
    id: 'phone_services',
    label: 'Τηλεφωνικές Υπηρεσίες',
    roles: [
      'multilingual_call_center', 'call_center_supervisor', 'call_center_agent',
      'telephonist', 'collections_agent',
    ],
  },
  {
    id: 'marketing_advertising',
    label: 'Marketing - Διαφήμιση - Επικοινωνία',
    roles: [
      'event_planner', 'social_media_manager', 'social_internet_marketing',
      'journalist', 'product_promoter', 'marketing_specialist', 'marketing_executive',
    ],
  },
  {
    id: 'beauty_fitness',
    label: 'Ομορφιά - Περιποίηση - Fitness',
    roles: [
      'beautician', 'gym_trainer', 'personal_trainer', 'nutritionist', 'hairdresser',
      'barber', 'massage_therapist', 'nail_technician', 'makeup_artist',
    ],
  },
  {
    id: 'it',
    label: 'Πληροφορική - Προγραμματιστές',
    roles: [
      'cyber_security_specialist', 'data_scientist', 'database_admin', 'devops_engineer',
      'erp_crm_specialist', 'it_support', 'it_administrator', 'network_admin',
      'qa_tester', 'software_developer', 'systems_engineer', 'tech_support_sales',
      'web_developer', 'web_designer', 'data_analyst',
    ],
  },
  {
    id: 'education',
    label: 'Εκπαίδευση',
    roles: [
      'elementary_teacher', 'special_education', 'seminar_instructor', 'secondary_teacher',
      'language_teacher', 'university_professor', 'translator', 'kindergarten_assistant',
      'tutor', 'teacher', 'babysitter',
    ],
  },
  {
    id: 'insurance_realestate',
    label: 'Ασφαλιστικά - Real Estate',
    roles: ['insurance_agent', 'real_estate_agent'],
  },
  {
    id: 'business_hr',
    label: 'Διοίκηση Επιχειρήσεων - HR - Στελέχη',
    roles: [
      'account_manager', 'project_manager', 'executive_director', 'business_manager',
      'hr_executive', 'iso_consultant', 'business_consultant', 'espa_consultant',
    ],
  },
  {
    id: 'design_arts',
    label: 'Design - Photo - Video - Audio - Arts',
    roles: [
      'cad_3d_designer', 'video_editor', 'videographer', 'graphic_designer',
      'interior_designer', 'actor', 'audiovisual_music', 'fashion_designer',
      'typographer', 'photographer',
    ],
  },
  {
    id: 'digital_ecom',
    label: 'Digital Marketing - Ecommerce',
    roles: [
      'content_creator', 'copywriter', 'digital_marketing_specialist',
      'ecommerce_specialist', 'ecommerce_manager', 'seo_specialist',
      'performance_marketer', 'eshop_admin',
    ],
  },
  {
    id: 'agriculture',
    label: 'Αγροτικά',
    roles: ['agronomist', 'forester', 'gardener', 'farm_worker'],
  },
  {
    id: 'legal',
    label: 'Νομικά',
    roles: ['lawyer', 'paralegal', 'legal_office_clerk'],
  },
  {
    id: 'maritime',
    label: 'Ναυτιλία',
    roles: ['shipping_executive', 'sailor', 'ship_engineer'],
  },
  {
    id: 'other',
    label: 'Άλλο',
    roles: ['other'],
  },
];

export const BUSINESS_TYPE_LABELS_EL: Record<string, string> = {
  hotel: 'Ξενοδοχείο',
  restaurant: 'Εστιατόριο',
  beach_bar: 'Beach Bar',
  cafe: 'Καφετέρια',
  villa: 'Βίλα',
  tourism_company: 'Τουριστική Εταιρεία',
  bar: 'Bar',
  resort: 'Resort',
  cruise: 'Κρουαζιέρα',
  other: 'Άλλο',
};

export const PAGINATION_DEFAULTS = {
  page: 1,
  perPage: 20,
  maxPerPage: 100,
} as const;

// ====== Job Form Labels ======

export const EMPLOYMENT_TYPE_LABELS_EL: Record<string, string> = {
  full_time: 'Πλήρης απασχόληση',
  part_time: 'Μερική απασχόληση',
  seasonal: 'Σεζόν',
};

export const SALARY_TYPE_LABELS_EL: Record<string, string> = {
  monthly: 'Ανά μήνα',
  hourly: 'Ανά ώρα',
  daily: 'Ανά ημέρα',
  negotiable: 'Συζητήσιμο',
};

export const SHIFT_TYPE_LABELS_EL: Record<string, string> = {
  morning: 'Πρωί',
  evening: 'Βράδυ',
  split: 'Σπαστό',
  flexible: 'Ευέλικτο',
};

export const EXPERIENCE_LABELS_EL: Record<string, string> = {
  none: 'Χωρίς εμπειρία',
  '1_2_years': '1-2 χρόνια',
  '3_plus_years': '3+ χρόνια',
};

export const BENEFITS_OPTIONS = [
  { key: 'housing_provided', label: '🏠 Διαμονή', desc: 'Στέγαση εργαζομένων' },
  { key: 'meals_provided', label: '🍽️ Σίτιση', desc: 'Παρέχεται φαγητό' },
  { key: 'transport_provided', label: '🚌 Μεταφορά', desc: 'Βοήθεια μετακίνησης' },
  { key: 'bonus_provided', label: '💰 Bonus', desc: 'Πριμ απόδοσης' },
  { key: 'insurance_provided', label: '⏰ Ευέλικτο ωράριο', desc: 'Ευελιξία στις ώρες' },
  { key: 'no_benefits', label: '❌ Χωρίς παροχές', desc: 'Δεν παρέχονται' },
] as const;
